import { getAllDocs, getDocById, getDocsByType, saveDoc } from '../src/lib/docs';
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

async function runTests() {
  console.log('--- STARTING OBSIDIAN VAULT TESTS ---');

  const vaultPath = process.env.OBSIDIAN_VAULT_PATH;
  if (!vaultPath) {
    console.error('OBSIDIAN_VAULT_PATH not set in env.');
    process.exit(1);
  }
  console.log(`Vault Path: ${vaultPath}`);

  // Test: Load all docs
  const allDocs = getAllDocs();
  console.log(`\n1. Loaded ${allDocs.length} documents from the vault.`);

  // Find a specific type
  const projects = getDocsByType('project');
  console.log(`2. Found ${projects.length} documents of type 'project'.`);

  // Create a new test document
  const testId = `test-doc-${Date.now()}`;
  const docPath = `Knowledge/${testId}.md`;
  
  console.log(`\n3. Saving new test document to ${docPath}...`);
  const newDoc = saveDoc(docPath, {
    frontmatter: {
      id: testId,
      title: 'Obsidian Test Doc',
      type: 'knowledge',
      category: 'testing',
      tags: ['test', 'obsidian', 'integration'],
      workspace: 'jarvis',
      tasks: [{ desc: 'verify integration', status: 'pending' }],
    },
    body: '## Test Content\nThis document was generated by the Jarvis test script to verify direct Obsidian filesystem integration.'
  });

  if (!newDoc) {
    console.error('Failed to create new doc.');
    process.exit(1);
  }

  console.log(`New document saved. Path: ${newDoc.path}`);

  // Fetch by ID
  console.log(`\n4. Fetching document by ID: ${testId}...`);
  const fetchedDoc = getDocById(testId);
  if (!fetchedDoc) {
    console.error(`Document with ID ${testId} not found in cache.`);
    process.exit(1);
  }
  console.log(`Document fetched successfully. Title: ${fetchedDoc.title}`);

  // Verify on disk
  console.log(`\n5. Verifying document on disk...`);
  const diskPath = path.join(vaultPath, docPath);
  if (!fs.existsSync(diskPath)) {
    console.error(`File does not exist on disk at expected path: ${diskPath}`);
    process.exit(1);
  }
  
  const rawDiskContent = fs.readFileSync(diskPath, 'utf8');
  const parsed = matter(rawDiskContent);
  console.log(`Disk frontmatter title: ${parsed.data.title}`);
  if (parsed.data.id !== testId || parsed.data.title !== 'Obsidian Test Doc') {
    console.error('Disk frontmatter does not match expected values.', parsed.data);
    process.exit(1);
  }
  console.log('Disk verification passed.');

  // Update existing doc
  console.log(`\n6. Updating document frontmatter...`);
  const updatedDoc = saveDoc(docPath, {
    frontmatter: {
      title: 'Obsidian Test Doc - Updated',
      updatedField: 'hello world',
      tasks: [{ desc: 'verify integration', status: 'completed' }],
    }
  });

  if (!updatedDoc) {
    console.error('Failed to update doc.');
    process.exit(1);
  }

  // Check the cache and disk
  const reFetchedDoc = getDocById(testId);
  console.log(`Re-fetched updated document title: ${reFetchedDoc?.title}`);

  const rawDiskContentUpdated = fs.readFileSync(diskPath, 'utf8');
  const parsedUpdated = matter(rawDiskContentUpdated);
  if (parsedUpdated.data.title !== 'Obsidian Test Doc - Updated') {
    console.error('Update did not persist to disk properly.', parsedUpdated.data);
    process.exit(1);
  }
  console.log('Document update successful.');

  console.log('\n--- ALL TESTS PASSED ---');
  process.exit(0);
}

runTests().catch(console.error);
